force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/RulePath__c/RulePath__c.object-meta.xml
<CustomObject>
    <label>RulePath</label>
    <nameField>
        <label>RulePath Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RulePaths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/RulePath__c/fields/SequenceKey__c.field-meta.xml
<CustomField>
    <fullName>SequenceKey__c</fullName>
    <description>Chave da sequencia, composta pelo Id do SObject e numero da sequencia</description>
    <formula>SObjectId__c + &apos;-&apos; + TEXT( Sequence__c )</formula>
    <inlineHelpText>Chave da sequencia, composta pelo Id da SObject e numero da sequencia</inlineHelpText>
    <label>SequenceKey</label>
    <type>Text</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/RulePath__c/fields/SObjectId__c.field-meta.xml
<CustomField>
    <fullName>SObjectId__c</fullName>
    <label>SObjectId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/RulePath__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em Análise</fullName>
            </value>
            <value>
                <fullName>Em Processamento</fullName>
            </value>
            <value>
                <fullName>Regra Atendida</fullName>
            </value>
            <value>
                <fullName>Regra nao Atendida</fullName>
            </value>
            <value>
                <fullName>Aguardando Pagamento</fullName>
            </value>
            <value>
                <fullName>Em Aprovacao</fullName>
                <label>Em Aprovação</label>
            </value>
            <value>
                <fullName>Faturamento Parcial Realizado</fullName>
            </value>
            <value>
                <fullName>Erro Integracao</fullName>
                <label>Erro Integração</label>
            </value>
            <value>
                <fullName>Aguardando Retorno da Integracao</fullName>
                <label>Aguardando Retorno da Integração</label>
            </value>
            <value>
                <fullName>Erro ao Executar Regra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Execution/RulePathDirector.cls
/**
 * @description: Class to enrich and update RulePath Object By a Sequence of Business Rules
 * @author: Guilherme Zwipp
 */
public with sharing class RulePathDirector {
   
    private static RulePathDirector instance = null;

    public static RulePathDirector getInstance(){
        if( instance == null ) instance = new RulePathDirector();
        return instance;
    }

    private RulePathEnricher enricher;
    private RulePathRepository repository;
    private RulePathFilter filter;

    private RulePathDirector(){
        this.enricher = RulePathEnricher.getInstance();
        this.repository = RulePathRepository.getInstance();
        this.filter = RulePathFilter.getInstance();
    }

    public List<RulePath__c> enrichNextRuleWithStatusInAnalisy( List<RulePath__c> rulesPaths ) {

        List<RulePath__c> rulesPathsInOrg = this.repository.findBySequenceKeysAndIsActiveAndIsDisabled(
            new Set<String>( Lists.byField( rulesPaths, 'SequenceKey__c' ) )
            , true, false
        );

        List<RulePath__c> quoteRulesPathsToFilter = this.repository.findBySObjectIdsAndStatusAndIsActivatedAndIsDisabled(
            this.provideSObjectIdsToPutNextRulesInAnalisy( rulesPathsInOrg )
            , '', true, false
        );

        return this.repository.save(
            this.enricher.withStatus( this.filter.byFirstSequence( quoteRulesPathsToFilter ), 'EM_ANALISE' )
        );
    }

    public Set<String> provideSObjectIdsToPutNextRulesInAnalisy( List<RulePath__c> rulesPaths ) {
        return this.provideSObjectIdsByRuleMetBySObjectId( this.provideRuleMetBySObjectId( rulesPaths ) );
    }

    private Map<String,Boolean> provideRuleMetBySObjectId( List<RulePath__c> rulesPaths ) {

        Map<String,Boolean> ruleMetBySObjectId = new Map<String,Boolean>();

        for( RulePath__c rulePath : rulesPaths ) {

            if( !ruleMetBySObjectId.containsKey( rulePath.SObjectId__c ) ) ruleMetBySObjectId.put( rulePath.SObjectId__c, true );

            if( ruleMetBySObjectId.get( rulePath.SObjectId__c ) == false ) continue;

            if( rulePath.Status__c == RulePathPicklistValues.STATUS_BY_CONST.get( 'REGRA_ATENDIDA' ) ) continue;

            ruleMetBySObjectId.put( rulePath.SObjectId__c, false );
        }

        return ruleMetBySObjectId;
    }

    private Set<String> provideSObjectIdsByRuleMetBySObjectId( Map<String,Boolean> ruleMetBySObjectId ) {

        Set<String> sObjectIds = new Set<String>();

        for( String sObjectId : ruleMetBySObjectId.keySet() ) {
            if( ruleMetBySObjectId.get( sObjectId ) == false ) continue;
            sObjectIds.add( sObjectId );
        }

        return sObjectIds;
    }

}