force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/RulePath__c/RulePath__c.object-meta.xml
<CustomObject>
    <label>RulePath</label>
    <nameField>
        <label>RulePath Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RulePaths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/RulePath__c/fields/isActivated__c.field-meta.xml
<CustomField>
    <fullName>isActivated__c</fullName>
    <formula>BusinessRulesPath__r.isActivated__c</formula>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/RulePath__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <formula>BusinessRulesPath__r.Sequence__c</formula>
    <label>Sequência</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/RulePath__c/fields/SObjectId__c.field-meta.xml
<CustomField>
    <fullName>SObjectId__c</fullName>
    <label>SObjectId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/RulePath__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em Análise</fullName>
            </value>
            <value>
                <fullName>Em Processamento</fullName>
            </value>
            <value>
                <fullName>Regra Atendida</fullName>
            </value>
            <value>
                <fullName>Regra nao Atendida</fullName>
            </value>
            <value>
                <fullName>Aguardando Pagamento</fullName>
            </value>
            <value>
                <fullName>Em Aprovacao</fullName>
                <label>Em Aprovação</label>
            </value>
            <value>
                <fullName>Faturamento Parcial Realizado</fullName>
            </value>
            <value>
                <fullName>Erro Integracao</fullName>
                <label>Erro Integração</label>
            </value>
            <value>
                <fullName>Aguardando Retorno da Integracao</fullName>
                <label>Aguardando Retorno da Integração</label>
            </value>
            <value>
                <fullName>Erro ao Executar Regra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Utils/Filters/RulePathFilter.cls
/**
 * @description: Class to filter RulePath__c collections
 * @author: Guilherme Zwipp
 */
public with sharing class RulePathFilter extends Filter {
        
    private static RulePathFilter instance = null;

    public static RulePathFilter getInstance(){
        if( instance == null ) instance = new RulePathFilter();
        return instance;
    }

    Decimal highestRuleSequence = 0;

    private RulePathFilter(){}

    public List<RulePath__c> byFirstSequence( List<RulePath__c> rulesPaths ) {

        Map<String,Map<Decimal,List<RulePath__c>>> activatedRulesPathsBySequenceBySObjectId = this.bySequenceBySObjectId( rulesPaths );

        List<RulePath__c> firstRulePath = new List<RulePath__c>();

        for( Map<Decimal,List<RulePath__c>> rulesPathsBySequence : activatedRulesPathsBySequenceBySObjectId.values() ) {

            for ( Decimal ruleSequence = 1; ruleSequence <= this.highestRuleSequence; ruleSequence++ ) {
                if( !rulesPathsBySequence.containsKey( ruleSequence ) ) continue;

                firstRulePath.addAll( rulesPathsBySequence.get( ruleSequence ) );
                break;
            }

        }

        return firstRulePath;

    }

    public Map<String,Map<Decimal,List<RulePath__c>>> bySequenceBySObjectId( List<RulePath__c> rulesPaths ) {
        Map<String,Map<Decimal,List<RulePath__c>>> activatedRulesPathsBySequenceBySObjectId = new Map<String,Map<Decimal,List<RulePath__c>>>();

        for( RulePath__c rulePath : rulesPaths ) {

            if( !rulePath.isActivated__c || rulePath.Sequence__c == null ) continue;

            String sObjectId = rulePath.SObjectId__c;

            if( !activatedRulesPathsBySequenceBySObjectId.containsKey( sObjectId ) ) {
                activatedRulesPathsBySequenceBySObjectId.put( sObjectId, new Map<Decimal,List<RulePath__c>>() );
            }

            if( !activatedRulesPathsBySequenceBySObjectId.get( sObjectId ).containsKey( rulePath.Sequence__c ) ) {
                activatedRulesPathsBySequenceBySObjectId.get( sObjectId ).put( rulePath.Sequence__c, new List<RulePath__c>() );
            }

            activatedRulesPathsBySequenceBySObjectId.get( sObjectId ).get( rulePath.Sequence__c ).add( rulePath );

            if( this.highestRuleSequence < rulePath.Sequence__c ) this.highestRuleSequence = rulePath.Sequence__c;

        }

        return activatedRulesPathsBySequenceBySObjectId;
    }

    public List<RulePath__c> byStatus( List<RulePath__c> rulesPaths, String status ) {
        
        List<RulePath__c> filteredRulesPaths = new List<RulePath__c>();

        for( RulePath__c rulePath : rulesPaths ) {
            if( rulePath.Status__c != RulePathPicklistValues.STATUS_BY_CONST.get( status ) ) continue;

            filteredRulesPaths.add( rulePath );
        }

        return filteredRulesPaths;
    }

}