force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/RulePath__c/RulePath__c.object-meta.xml
<CustomObject>
    <label>RulePath</label>
    <nameField>
        <label>RulePath Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RulePaths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/RulePath__c/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <formula>BusinessRulesPath__r.BusinessRulesValidation__r.ClassName__c</formula>
    <label>ClassName</label>
    <type>Text</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/RulePath__c/fields/ExecuteSubRule__c.field-meta.xml
<CustomField>
    <fullName>ExecuteSubRule__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para identificar se a sub-regra deve ser realizada ou não.

Caso o valor seja true, a regra será realizada.
Caso o valor seja false, a regra deverá ser ignorada (sendo atualizada automaticamente para &quot;regra atendida&quot;).</description>
    <inlineHelpText>Campo para identificar se a sub-regra deve ser realizada ou não.

Caso o valor seja true, a regra será realizada.
Caso o valor seja false, a regra deverá ser ignorada (sendo atualizada automaticamente para &quot;regra atendida&quot;).</inlineHelpText>
    <label>Executar Sub-Regra</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/RulePath__c/fields/isActivated__c.field-meta.xml
<CustomField>
    <fullName>isActivated__c</fullName>
    <formula>BusinessRulesPath__r.isActivated__c</formula>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/RulePath__c/fields/isDisabled__c.field-meta.xml
<CustomField>
    <fullName>isDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo identificador para saber se o conjunto de regras ainda esta em processo de análise, caso esteja marcada com o valor &quot;false&quot;, o conjunto de regras ainda esta em andamento, caso esteja com o valor &quot;true&quot;, o conjunto de regras que essa regra pertence foi cancelado ou alguma regra nao foi atendida.</description>
    <inlineHelpText>Campo identificador para saber se o conjunto de regras ainda esta em processo de análise, caso esteja marcada com o valor &quot;false&quot;, o conjunto de regras ainda esta em andamento, caso esteja com o valor &quot;true&quot;, o conjunto de regras que essa regra pertence foi cancelado ou alguma regra nao foi atendida.</inlineHelpText>
    <label>Está Desativado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/RulePath__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <formula>BusinessRulesPath__r.Sequence__c</formula>
    <label>Sequência</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/RulePath__c/fields/SequenceKey__c.field-meta.xml
<CustomField>
    <fullName>SequenceKey__c</fullName>
    <description>Chave da sequencia, composta pelo Id do SObject e numero da sequencia</description>
    <formula>SObjectId__c + &apos;-&apos; + TEXT( Sequence__c )</formula>
    <inlineHelpText>Chave da sequencia, composta pelo Id da SObject e numero da sequencia</inlineHelpText>
    <label>SequenceKey</label>
    <type>Text</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/RulePath__c/fields/SObjectId__c.field-meta.xml
<CustomField>
    <fullName>SObjectId__c</fullName>
    <label>SObjectId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/RulePath__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em Análise</fullName>
            </value>
            <value>
                <fullName>Em Processamento</fullName>
            </value>
            <value>
                <fullName>Regra Atendida</fullName>
            </value>
            <value>
                <fullName>Regra nao Atendida</fullName>
            </value>
            <value>
                <fullName>Aguardando Pagamento</fullName>
            </value>
            <value>
                <fullName>Em Aprovacao</fullName>
                <label>Em Aprovação</label>
            </value>
            <value>
                <fullName>Faturamento Parcial Realizado</fullName>
            </value>
            <value>
                <fullName>Erro Integracao</fullName>
                <label>Erro Integração</label>
            </value>
            <value>
                <fullName>Aguardando Retorno da Integracao</fullName>
                <label>Aguardando Retorno da Integração</label>
            </value>
            <value>
                <fullName>Erro ao Executar Regra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Utils/Repositories/RulePathRepository.cls
/**
 * @description: Repository for RulePath__c Object
 * @author: Guilherme Zwipp
 */
public virtual with sharing class RulePathRepository extends AbstractRepository {
    
    private static RulePathRepository instance = null;

    public static RulePathRepository getInstance() {
        if( instance == null ) instance = new RulePathRepository();
        return instance;
    }

    protected RulePathRepository(){}

    public virtual List<RulePath__c> findByIds( List<String> ids ) {
        return [
            SELECT
                Id
                , SObjectId__c
            FROM
                RulePath__c
            WHERE Id IN :ids
        ];
    }

    public virtual List<RulePath__c> findBySObjectIdsAndClassNameAndIsDisabled( List<String> sObjectIds, String className, Boolean isDisabled ) {
        return [
            SELECT
                Id
                , Status__c
                , SObjectId__c
                , Sequence__c
                , isActivated__c
            FROM
                RulePath__c
            WHERE SObjectId__c IN :sObjectIds
                AND ClassName__c = :className
                AND isDisabled__c = :isDisabled
        ];
    }

    public virtual List<RulePath__c> findBySequenceKeysAndIsActiveAndIsDisabled( Set<String> sequenceKeys, Boolean isActivated, Boolean isDisabled ) {
        return [
            SELECT
                Id
                , Status__c
                , SObjectId__c
                , Sequence__c
            FROM
                RulePath__c
            WHERE SequenceKey__c IN :sequenceKeys
                AND isActivated__c = :isActivated
                AND isDisabled__c = :isDisabled
        ];
    }

    public virtual List<RulePath__c> findByClassNamesAndStatusAndIsDisabled( List<String> classNames, String status, Boolean isDisabled ){
        return[
            SELECT
                Id
                , SObjectId__c
                , Status__c
            FROM
                RulePath__c
            WHERE ClassName__c IN :classNames
                AND Status__c = :status
                AND isDisabled__c = :isDisabled
        ];
    }

    public virtual List<RulePath__c> findBySObjectIdsAndIsActiveAndIsDisabled( Set<String> sObjectIds, Boolean isActivated, Boolean isDisabled ){
        return[
            SELECT
                Id
                , SObjectId__c
                , Status__c
                , ExecuteSubRule__c
            FROM
                RulePath__c
            WHERE SObjectId__c IN :sObjectIds
                AND isActivated__c = :isActivated
                AND isDisabled__c = :isDisabled
        ];
    }

    public virtual List<RulePath__c> findBySObjectIdsAndStatusAndIsActivatedAndIsDisabled( Set<String> sObjectIds, String status, Boolean isActivated, Boolean isDisabled ){
        return[
            SELECT
                Id
                , SObjectId__c
                , Status__c
                , isActivated__c
                , Sequence__c
                , ExecuteSubRule__c
            FROM
                RulePath__c
            WHERE SObjectId__c IN :sObjectIds
                AND Status__c = :status
                AND isActivated__c = :isActivated
                AND isDisabled__c = :isDisabled
        ];
    }

}