force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesSetting__c/BusinessRulesSetting__c.object-meta.xml
<CustomObject>
    <label>BusinessRulesSetting</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BusinessRulesSettings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesSetting__c/fields/isActivated__c.field-meta.xml
<CustomField>
    <fullName>isActivated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isActivated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesSetting__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesSetting__c/fields/RuleKey__c.field-meta.xml
<CustomField>
    <fullName>RuleKey__c</fullName>
    <label>RuleKey</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Utils/Factories/BusinessRulesSettingFactory.cls
/**
 * @description: Factory to create BusinessRulesSetting__c objects in test context
 * @author: Guilherme Zwipp
 */
@isTest
public with sharing class BusinessRulesSettingFactory {

    public static BusinessRulesSetting__c buildNew( String name, Boolean isActivated, String ruleKey, String objectName ) {
        return new BusinessRulesSetting__c(
            Name = name
            , isActivated__c = isActivated
            , RuleKey__c = ruleKey
            , Object__c = objectName
        );
    }

    public class DefaultRT extends SObjectFactory{

        public DefaultRT( String name, Boolean isActivated, String ruleKey, String objectName ) {
            super( buildNew( name, isActivated, ruleKey, objectName ) );
        }

    }

    public static BusinessRulesSetting__c fromJson( String payload ){
        return (BusinessRulesSetting__c) JSON.deserialize( payload, BusinessRulesSetting__c.class );
    }
    
    public static List<BusinessRulesSetting__c> fromJsonArray( String payload ){
        return (List<BusinessRulesSetting__c>) JSON.deserialize( payload, List<BusinessRulesSetting__c>.class );
    }

}