force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/RulePathSObjectSetting__c/RulePathSObjectSetting__c.object-meta.xml
<CustomObject>
    <label>RulePathSObjectSetting</label>
    <nameField>
        <label>RulePathRepositoryParameterizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RulePathSObjectSettings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/RulePathSObjectSetting__c/fields/FieldsToUseInQuery__c.field-meta.xml
<CustomField>
    <fullName>FieldsToUseInQuery__c</fullName>
    <inlineHelpText>Values separated by ,</inlineHelpText>
    <label>FieldsToUseInQuery</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Utils/Builders/BR_RulePathSObjectSettingBuilder.cls
/**
 * @description: Class responsible to build RulePathSObjectSetting__c SObject
 * @author: Guilherme Zwipp
 */
public with sharing class BR_RulePathSObjectSettingBuilder {

    private RulePathSObjectSetting__c rulePathSObjectSetting;

    public BR_RulePathSObjectSettingBuilder() {
        rulePathSObjectSetting = new RulePathSObjectSetting__c();
    }

    public BR_RulePathSObjectSettingBuilder withName( String name ) {
        this.rulePathSObjectSetting.Name = name;
        return this;
    }

    public BR_RulePathSObjectSettingBuilder withFieldsToUseInQuery( String fieldsToUseInQuery ) {
        this.rulePathSObjectSetting.FieldsToUseInQuery__c = fieldsToUseInQuery;
        return this;
    }

    public RulePathSObjectSetting__c build(){
        return this.rulePathSObjectSetting;
    }

}