force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/RulePathSObjectSetting__c/RulePathSObjectSetting__c.object-meta.xml
<CustomObject>
    <label>RulePathSObjectSetting</label>
    <nameField>
        <label>RulePathRepositoryParameterizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RulePathSObjectSettings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/RulePathSObjectSetting__c/fields/FieldsToUseInQuery__c.field-meta.xml
<CustomField>
    <fullName>FieldsToUseInQuery__c</fullName>
    <inlineHelpText>Values separated by ,</inlineHelpText>
    <label>FieldsToUseInQuery</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Creation/RulePathSObjectSettingRepository.cls
/**
 * @description: Repository for RulePathSObjectSetting__c Object
 * @author: Guilherme Zwipp
 */
public virtual class RulePathSObjectSettingRepository {

    private static RulePathSObjectSettingRepository instance = null;

    public static RulePathSObjectSettingRepository getInstance() {
        if( instance == null ) instance = new RulePathSObjectSettingRepository();
        return instance;
    }

    protected RulePathSObjectSettingRepository() {}

    public virtual RulePathSObjectSetting__c findByName( String name ) {
        List<RulePathSObjectSetting__c> rulePathSObjectSettings = this.findByNames( new List<String>{name} );
        return rulePathSObjectSettings.isEmpty() ? null : rulePathSObjectSettings[0];
    }

    public virtual List<RulePathSObjectSetting__c> findByNames( List<String> names ) {
        return[
            SELECT
                Id
                , FieldsToUseInQuery__c
            FROM
                RulePathSObjectSetting__c
            WHERE Name IN :names
        ];
    }

}