force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesPath__c/BusinessRulesPath__c.object-meta.xml
<CustomObject>
    <label>BusinessRulesPath</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BusinessRulesPaths</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesPath__c/fields/BusinessRulesSetting__c.field-meta.xml
<CustomField>
    <fullName>BusinessRulesSetting__c</fullName>
    <label>BusinessRulesSetting</label>
    <referenceTo>BusinessRulesSetting__c</referenceTo>
    <relationshipName>BusinessRulesPaths</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesPath__c/fields/isActivated__c.field-meta.xml
<CustomField>
    <fullName>isActivated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesPath__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequência</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesSetting__c/BusinessRulesSetting__c.object-meta.xml
<CustomObject>
    <label>BusinessRulesSetting</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BusinessRulesSettings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesSetting__c/fields/isActivated__c.field-meta.xml
<CustomField>
    <fullName>isActivated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isActivated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesSetting__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesSetting__c/fields/RuleKey__c.field-meta.xml
<CustomField>
    <fullName>RuleKey__c</fullName>
    <label>RuleKey</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Utils/Repositories/BusinessRulesSettingRepository.cls
/**
 * @description: Class to provide stored BusinessRulesSetting__c collections
 * @author: Guilherme Zwipp
 */
public virtual class BusinessRulesSettingRepository extends AbstractRepository {
    
    private static BusinessRulesSettingRepository instance = null;

    public static BusinessRulesSettingRepository getInstance() {
        if( instance == null ) instance = new BusinessRulesSettingRepository();
        return instance;
    }

    @TestVisible
    private BusinessRulesSettingRepository(){}

    public virtual List<BusinessRulesSetting__c> findByObjectNameAndIsActivatedAndQueryLimit( String objectName, Boolean isActivated, Integer queryLimit ) {
        return [
            SELECT
                Id
                , Name
                , RuleKey__c
                , isActivated__c
                , Object__c
                , (
                    SELECT
                        Id
                        , Name
                        , Sequence__c
                        , isActivated__c
                    FROM
                        BusinessRulesPaths__r
                )
            FROM
                BusinessRulesSetting__c
            WHERE Object__c = :objectName
                AND isActivated__c = :isActivated
            ORDER BY CreatedDate DESC
            LIMIT :queryLimit
        ];
    }

    public virtual List<BusinessRulesSetting__c> findByObjectNamesAndIsActivatedAndQueryLimit( Set<String> objectNames, Boolean isActivated, Integer queryLimit ) {
        return [
            SELECT
                Id
                , Name
                , RuleKey__c
                , isActivated__c
                , Object__c
                , (
                    SELECT
                        Id
                        , Name
                        , Sequence__c
                        , isActivated__c
                    FROM
                        BusinessRulesPaths__r
                )
            FROM
                BusinessRulesSetting__c
            WHERE Object__c IN :objectNames
                AND isActivated__c = :isActivated
            ORDER BY CreatedDate DESC
            LIMIT :queryLimit
        ];
    }

    @TestVisible
    private static void setMock( BusinessRulesSettingRepository mockInstance ) {
        instance = mockInstance;
    }

}