force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesPath__c/BusinessRulesPath__c.object-meta.xml
<CustomObject>
    <label>BusinessRulesPath</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BusinessRulesPaths</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/RulePath__c/RulePath__c.object-meta.xml
<CustomObject>
    <label>RulePath</label>
    <nameField>
        <label>RulePath Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RulePaths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/RulePath__c/fields/BusinessRulesPath__c.field-meta.xml
<CustomField>
    <fullName>BusinessRulesPath__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>BusinessRulesPath</label>
    <referenceTo>BusinessRulesPath__c</referenceTo>
    <relationshipLabel>RulePaths</relationshipLabel>
    <relationshipName>RulePaths</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/RulePath__c/fields/SObjectId__c.field-meta.xml
<CustomField>
    <fullName>SObjectId__c</fullName>
    <label>SObjectId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Utils/Builders/RulePathBuilder.cls
/**
 * @description: Class responsible to build RulePath__c SObject
 * @author: Guilherme Zwipp
 */
public with sharing class RulePathBuilder {

    private RulePath__c rulePath;

    public RulePathBuilder() {
        this.rulePath = new RulePath__c();
    }

    public RulePathBuilder withSObjectId( String sObjectId ) {
        this.rulePath.SObjectId__c = sObjectId;

        return this;
    }

    public RulePathBuilder withBusinessRulesPathId( String businessRulesPathId ) {
        this.rulePath.BusinessRulesPath__c = businessRulesPathId;

        return this;
    }

    public RulePathBuilder withName( String name ) {
        this.rulePath.Name = name;

        return this;
    }

    public RulePath__c build() {
        return this.rulePath;
    }

}