force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesPath__c/BusinessRulesPath__c.object-meta.xml
<CustomObject>
    <label>BusinessRulesPath</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BusinessRulesPaths</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesPath__c/fields/BusinessRulesSetting__c.field-meta.xml
<CustomField>
    <fullName>BusinessRulesSetting__c</fullName>
    <label>BusinessRulesSetting</label>
    <referenceTo>BusinessRulesSetting__c</referenceTo>
    <relationshipName>BusinessRulesPaths</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesPath__c/fields/BusinessRulesValidation__c.field-meta.xml
<CustomField>
    <fullName>BusinessRulesValidation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>BusinessRulesValidation</label>
    <referenceTo>BusinessRulesValidation__c</referenceTo>
    <relationshipName>BusinessRulesPaths</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesPath__c/fields/isActivated__c.field-meta.xml
<CustomField>
    <fullName>isActivated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesPath__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequência</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesSetting__c/BusinessRulesSetting__c.object-meta.xml
<CustomObject>
    <label>BusinessRulesSetting</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BusinessRulesSettings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesSetting__c/fields/isActivated__c.field-meta.xml
<CustomField>
    <fullName>isActivated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isActivated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesValidation__c/BusinessRulesValidation__c.object-meta.xml
<CustomObject>
    <label>BusinessRulesValidation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BusinessRulesValidations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/FrameWork/MadeByMe/BusinessRules/Utils/Factories/BR_BusinessRulesPathFixtureFactory.cls
/**
 * @description: Fixture Factory to create BusinessRulesPath__c objects in test context
 * @author: Guilherme Zwipp
 */
@isTest
public inherited sharing class BR_BusinessRulesPathFixtureFactory {

    public static BusinessRulesPath__c createRecord( String name, Id businessRulesSettingId, Boolean isActivated, Integer sequence, Id businessRulesValidationId ) {
        return createRecord( buildRecord( name, businessRulesSettingId, isActivated, sequence, businessRulesValidationId ) );
    }
        
    public static BusinessRulesPath__c buildRecord( String name, Id businessRulesSettingId, Boolean isActivated, Integer sequence, Id businessRulesValidationId ) {
        return new BusinessRulesPath__c(
            Name = name
            , BusinessRulesSetting__c = businessRulesSettingId
            , isActivated__c = isActivated
            , Sequence__c = sequence
            , BusinessRulesValidation__c = businessRulesValidationId
        );
    }

    public static BusinessRulesPath__c createRecord( BusinessRulesPath__c businessRulesPath ) {
        insert businessRulesPath;
        return businessRulesPath;
    }

    public static Map<String,SObject> exampleIntegratedScenario( Id businessRulesSettingId, Boolean isActivated, Integer sequence ) {
        Map<String,SObject> records = new Map<String,SObject>();
        
        BusinessRulesValidation__c businessRulesValidation = BR_BusinessRulesValidationFixtureFactory.createRecord(
            'BR_ExampleValidationRule'
            , 'BR_ExampleValidationRule'
        );
        records.put( 'BusinessRulesValidation__c', businessRulesValidation );

        BusinessRulesPath__c businessRulesPath = createRecord(
            'BR_ExampleValidationRule'
            , businessRulesSettingId
            , isActivated
            , sequence
            , businessRulesValidation.Id
        );
        records.put( 'BusinessRulesPath__c', businessRulesPath );

        return records;
    }

    public static Map<String,SObject> exampleTwoIntegratedScenario( Id businessRulesSettingId, Boolean isActivated, Integer sequence ) {
        Map<String,SObject> records = new Map<String,SObject>();
        
        BusinessRulesValidation__c businessRulesValidation = BR_BusinessRulesValidationFixtureFactory.createRecord(
            'BR_ExampleTwoValidationRule'
            , 'BR_ExampleTwoValidationRule'
        );
        records.put( 'BusinessRulesValidation__c', businessRulesValidation );

        BusinessRulesPath__c businessRulesPath = createRecord(
            'BR_ExampleTwoValidationRule'
            , businessRulesSettingId
            , isActivated
            , sequence
            , businessRulesValidation.Id
        );
        records.put( 'BusinessRulesPath__c', businessRulesPath );

        return records;
    }

}