force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesPath__c/BusinessRulesPath__c.object-meta.xml
<CustomObject>
    <label>BusinessRulesPath</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BusinessRulesPaths</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesPath__c/fields/BusinessRulesSetting__c.field-meta.xml
<CustomField>
    <fullName>BusinessRulesSetting__c</fullName>
    <label>BusinessRulesSetting</label>
    <referenceTo>BusinessRulesSetting__c</referenceTo>
    <relationshipName>BusinessRulesPaths</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesPath__c/fields/BusinessRulesValidation__c.field-meta.xml
<CustomField>
    <fullName>BusinessRulesValidation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>BusinessRulesValidation</label>
    <referenceTo>BusinessRulesValidation__c</referenceTo>
    <relationshipName>BusinessRulesPaths</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesPath__c/fields/isActivated__c.field-meta.xml
<CustomField>
    <fullName>isActivated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesPath__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequência</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesSetting__c/BusinessRulesSetting__c.object-meta.xml
<CustomObject>
    <label>BusinessRulesSetting</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BusinessRulesSettings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesSetting__c/fields/isActivated__c.field-meta.xml
<CustomField>
    <fullName>isActivated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isActivated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesValidation__c/BusinessRulesValidation__c.object-meta.xml
<CustomObject>
    <label>BusinessRulesValidation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BusinessRulesValidations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/FrameWork/MadeByMe/BusinessRules/Utils/Factories/BR_BusinessRulesPathFactory.cls
/**
 * @description: Factory to create BusinessRulesPath__c objects in test context
 * @author: Guilherme Zwipp
 */
public with sharing class BR_BusinessRulesPathFactory {
    
    public static BusinessRulesPath__c buildNew( String name, Id businessRulesSettingId, Boolean isActivated, Integer sequence, Id businessRulesValidationId ) {
        return new BusinessRulesPath__c(
            Name = name
            , BusinessRulesSetting__c = businessRulesSettingId
            , isActivated__c = isActivated
            , Sequence__c = sequence
            , BusinessRulesValidation__c = businessRulesValidationId
        );
    }

    public class BR_ExampleValidationRule extends SObjectFactory{

        public BR_ExampleValidationRule( Id businessRulesSettingId, Boolean isActivated, Integer sequence ){
            super(
                buildNew(
                    'BR_ExampleValidationRule'
                    , businessRulesSettingId
                    , isActivated
                    , sequence
                    , new BR_BusinessRulesValidationFactory.BR_ExampleValidationRule( 'BR_ExampleValidationRule' ).createRecord().Id
                )
            );
        }
    }

    public class BR_ExampleTwoValidationRule extends SObjectFactory{

        public BR_ExampleTwoValidationRule( Id businessRulesSettingId, Boolean isActivated, Integer sequence ){
            super(
                buildNew(
                    'BR_ExampleTwoValidationRule'
                    , businessRulesSettingId
                    , isActivated
                    , sequence
                    , new BR_BusinessRulesValidationFactory.BR_ExampleTwoValidationRule( 'BR_ExampleTwoValidationRule' ).createRecord().Id
                )
            );
        }
    }

}