force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesValidation__c/BusinessRulesValidation__c.object-meta.xml
<CustomObject>
    <label>BusinessRulesValidation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BusinessRulesValidations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesValidation__c/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <label>Nome da Classe</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Utils/Factories/BR_BusinessRulesValidationFixtureFactory.cls
/**
 * @description: Factory to create BusinessRulesValidation__c objects in test context
 * @author: Guilherme Zwipp
 */
@isTest
public inherited sharing class BR_BusinessRulesValidationFixtureFactory {

    public static BusinessRulesValidation__c createRecord( String name, String className ) {
        return createRecord( buildRecord( name, className ) );
    }
        
    public static BusinessRulesValidation__c buildRecord( String name, String className ) {
        return new BusinessRulesValidation__c(
            Name = name
            , ClassName__c = className
        );
    }

    public static BusinessRulesValidation__c createRecord( BusinessRulesValidation__c businessRulesValidation ) {
        insert businessRulesValidation;
        return businessRulesValidation;
    }

}