force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesValidation__c/BusinessRulesValidation__c.object-meta.xml
<CustomObject>
    <label>BusinessRulesValidation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BusinessRulesValidations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/FrameWork/MadeByMe/BusinessRules/Metadatas/objects/BusinessRulesValidation__c/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <label>Nome da Classe</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/FrameWork/MadeByMe/BusinessRules/Utils/Factories/BR_BusinessRulesValidationFactory.cls
/**
 * @description: Factory to create BusinessRulesValidation__c objects in test context
 * @author: Guilherme Zwipp
 */
public with sharing class BR_BusinessRulesValidationFactory {
    
    public static BusinessRulesValidation__c buildNew( String name, String className ) {
        return new BusinessRulesValidation__c(
            Name = name
            , ClassName__c = className
        );
    }

    public class BR_ExampleValidationRule extends SObjectFactory{

        public BR_ExampleValidationRule( String name ){
            super( buildNew( name, 'BR_ExampleValidationRule' ) );
        }
    }

    public class BR_ExampleTwoValidationRule extends SObjectFactory{

        public BR_ExampleTwoValidationRule( String name ){
            super( buildNew( name, 'BR_ExampleTwoValidationRule' ) );
        }
    }

}